config/routes.rb
Rails.application.routes.draw do


  root 'article#index'

  # Articles
  resources :article

  post 'article/make_article_public'


  post 'comment/create'

  post 'upvote/create'

  # Authentification
  devise_for :users

  # Comments



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content

  has_many :comments,dependent: :destroy
  has_many :upvotes,dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true


  scope :availables, -> { where(private: false) }

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

end

app/models/upvote.rb
class Upvote < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates_uniqueness_of :user_id, :scope => :article_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :articles, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  before_action :authenticate_user!, only: %i[new, create, update, delete]

  def index
    @articles = Article.availables
    if current_user
      my_articles = Article.where(user_id: current_user.id)
      @articles = @articles + my_articles
    end
  end

  def show
    @article = Article.find(params[:id])
    if current_user
      @allready_voted = @article.upvotes.where(user_id: current_user.id).present?
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))
    @article.save

    if @article.save
      redirect_to root_path
    else
      render('new')
    end
  end

  def make_article_public
    article = Article.find(params[:article_id])
    article[:private] = false
    article.save

    puts(article.save)

    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :private)
  end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user!

  def create
    puts params
    @comment = Comment.new(comment_params)
    @comment.save

    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :content, :article_id)
  end

end

app/controllers/upvote_controller.rb
class UpvoteController < ApplicationController
  before_action :authenticate_user!

  def create
    new_upvote = Upvote.new(upvote_params.merge(user_id: current_user.id))
    new_upvote.save
    @upvote_count = Article.find(params[:article_id]).upvotes.length

    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private

  def upvote_params
    params.permit(:article_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/article/_article_card.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= article.title %></h5>
    <div class="article_card__content">
      <%= article.content.to_s %>
    </div>
    <p class="card-text"><small class="text-muted">Créé le <%= article.created_at.strftime("%d/%m/%Y")
    %> </small></p>
    <% if article[:private] %>
      <p id="private_info">Article privé</p>
      <%= link_to "Rendre public",article_make_article_public_path(:article_id => article.id ), :method => :post, remote: true, id: "go_public_btn"  %>
    <% end %>
  </div>
</div>

app/views/article/index.html.erb
<div class="container p-5">
  <div class="row">
    <% @articles.each do |article| %>
      <%= link_to "article/#{article.id}", method: :get, class: "article_card", 'data-searchbar-target' => "article", 'data-title' => "#{article.title.downcase}" do %>
        <%= render partial: "article_card", locals: {article: article} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/article/make_article_public.js.erb
$("#private_info").remove()
$('#go_public_btn').remove()

app/views/article/new.html.erb
<div class="container">
  <%= bootstrap_form_with(model: @article, url: "/article", method: "POST") do |f| %>
    <%= f.text_field :title %>
    <%= f.rich_text_area :content%>
    <%= f.radio_button :private, "article privé", :checked => true %>
    <%= f.radio_button :private, "article public", :checked => false %>
    <%= f.submit "Publier" %>
  <% end %>
</div>

app/views/article/show.html.erb
<div class="article">
  <div class="container">
    <div class="article__header">
      <div class="article__title-section">
        <h1><%=@article.title %></h1>
      </div>
    </div>
    <div class="article__content-section">
      <div class="article__content">
        <%= @article.content %>
      </div>
    </div>
    <div class="article__comment-section">
      <h4>Commentaires</h4>
      <div class="row">
        <div class="col-sm-12 col-md-8">
          <div id="comment__container" class="article__comment">
            <%  @article.comments.each do |comment| %>
              <%= render partial: "./comment/comment_card", locals: { comment: comment} %>
            <%end %>
          </div>
        </div>

       <div class="col-sm-12 col-md-4">
         <div class="article__create__comment-section">
           <% if user_signed_in?  %>
             <%= render partial: "./upvote/upvote_component", locals: {article: @article} %>

           <%= render partial: "./comment/comment_form", locals: {user: current_user, article: @article} %>

             <% end %>


         </div>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/comment/_comment_card.html.erb
<div class="comment_card">
  <h6><%= comment.user.name %></h6>
  <p><%= comment.content %></p>
  <p><%= comment.created_at.strftime("%d/%m/%Y") %></p>


</div>

app/views/comment/_comment_form.html.erb
<div class="comment__form">
  <h2>Laissez un coommentaire</h2>
  <form action='/comment/create' name="comment" method='post' data-remote='true' class="">
    <div class="field">
      <input type="hidden" name="comment[user_id]" value="<%= user.id %>">
    </div>
    <div class="field">
      <input type="hidden" name="comment[article_id]" value="<%= article.id %>">
    </div>
    <div class="field">
      <textarea name="comment[content]" id="" cols="30" rows="10" autofocus="true"></textarea>

    </div>
    <div class="field">
      <input type="submit" class="btn btn-primary">
    </div>
  </form>


</div>

app/views/comment/create.js.erb
$("#comment__container").prepend("<%= escape_javascript render(partial: "comment_card", locals: {comment: @comment}) %>");

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Medium_blog", root_path, class: "navbar-brand" %>

    <% if controller.action_name == "index" %>
      <form class="d-flex">
        <input data-searchbar-target="searchbarinput" data-action="input->searchbar#change" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button data-action="click->searchbar#search" class="btn btn-outline-success" >Search</button>
      </form>
    <% end %>

    <div>
      <% if user_signed_in? %>
        <%= link_to 'Créer un article', new_article_path%>
        <%= link_to 'Se déconnecter', destroy_user_session_path, :method => :delete%>
      <% else %>
        <%= link_to "S'inscrire", new_user_registration_path %>
        <%= link_to "Se connecter", new_user_session_path %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediumBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body data-controller="searchbar">
  <%= render partial: "layouts/navbar" %>
    <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/upvote/_upvote_component.html.erb
<h5 id="upvote_count_component">Votes : <%= article.upvotes.length %></h5>

<% if !@allready_voted %>
  <%= link_to "Ajouter un vote",upvote_create_path(:article_id => article.id ), :method => :post, remote: true, id: "upvote_btn"  %>
  <% end %>

app/views/upvote/create.js.erb
$("#upvote_count_component").text("Votes : <%=@upvote_count %>")
$('#upvote_btn').remove()